import type { GameMeta } from '../lib/types'
export const catalog: GameMeta[] = [
  {
    id: 'zhajinhua',
    name: '炸金花',
    english: 'THREE CARDS, ONE WINNER',
    tag: '酒局心理战',
    description: '三张底牌，拼手气也拼胆量。',
    rule: '每人三张牌，轮流闷牌、跟注、加注、比牌或弃牌，留到最后的人赢。豹子 > 顺金 > 金花 > 顺子 > 对子 > 散牌；A23 最小，平牌发起比牌者输。每位输家喝 1 小口，可用饮料代替或跳过。积分仅用于牌局，房间设置可切换轻松挑战、开启杂色 235 吃豹子。',
    color: 'gold',
    icon: 'poker',
    duration: '2–5 分钟',
    maxPlayers: 17,
  },
  {
    id: 'vote',
    name: '匿名投票',
    english: 'WHO’S THE ONE',
    tag: '聚会破冰王',
    description: '谁才是大家心中的那个人？',
    rule: '看到问题后，悄悄投给一位玩家。全员提交或 45 秒结束后揭晓，最高票接受轻松挑战，并列也算哦。',
    color: 'lime',
    icon: 'vote',
    duration: '1–2 分钟',
  },
  {
    id: 'truth',
    name: '真心话大冒险',
    english: 'TRUTH OR DARE',
    tag: '打开心扉',
    description: '聊点真心的，做点大胆的。',
    rule: '系统随机选一人，选择真心话或大冒险并抽卡。每个任务都可以自愿跳过，开心和舒服最重要。',
    color: 'purple',
    icon: 'cards',
    duration: '2–3 分钟',
  },
  {
    id: 'roulette',
    name: '幸运轮盘',
    english: 'SPIN YOUR LUCK',
    tag: '心跳加速',
    description: '下一位幸运儿，会是谁？',
    rule: '房主转动轮盘，由服务器确定结果。左右顺序按照房间玩家列表，抽中“指定一人”时由转盘玩家选择。',
    color: 'orange',
    icon: 'wheel',
    duration: '1 分钟',
  },
  {
    id: 'dice',
    name: '摇骰子',
    english: 'ROLL WITH IT',
    tag: '运气对决',
    description: '一掷定胜负，看看谁的手气好。',
    rule: '每位玩家摇一次骰子，点数由服务器生成。全员完成后揭晓排名，默认最小点数接受挑战，可在房间设置中切换。',
    color: 'blue',
    icon: 'dice',
    duration: '1 分钟',
  },
  {
    id: 'compatibility',
    name: '默契测试',
    english: 'ON THE SAME PAGE',
    tag: '默契搭子',
    description: '你的选择，TA 能猜中吗？',
    rule: '随机选择两位玩家，分别秘密选择一个答案。双方完成后同时揭晓，答案一致时两人各获得 1 点默契分。',
    color: 'pink',
    icon: 'heart',
    duration: '1–2 分钟',
  },
]
