import { test, expect, type Page } from '@playwright/test'
const waitReady = async (page: Page) => {
  await expect(page.getByRole('button', { name: '连接状态：已连接', exact: true })).toBeVisible()
}
const start = async (page: Page, game: string) => {
  await page
    .locator('.lobby-game')
    .filter({ has: page.getByRole('heading', { name: game, exact: true }) })
    .click()
  await page.getByRole('button', { name: `开始游戏 · ${game}`, exact: true }).click()
  await expect(page.locator('.game-stage')).toBeVisible()
  await expect(page.locator('.countdown-overlay')).toHaveCount(0)
}
test('two players play all five games, refresh, reconnect, and transfer ownership', async ({
  browser,
}) => {
  const ownerContext = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const guestContext = await browser.newContext({ viewport: { width: 375, height: 812 } })
  const owner = await ownerContext.newPage(),
    guest = await guestContext.newPage()
  const base = test.info().project.use.baseURL as string
  await owner.goto(base)
  await owner.getByRole('button', { name: '创建房间', exact: true }).click()
  await expect(owner).toHaveURL(/\/profile/)
  await owner.getByLabel('你的昵称').fill('小辉')
  await owner.getByRole('button', { name: '准备好了，入场' }).click()
  await expect(owner).toHaveURL(/\/room\/[0-9]{6}/)
  await waitReady(owner)
  const code = owner.url().split('/').pop()!
  await guest.goto(`${base}/join`)
  await guest.getByLabel('6 位房间码').fill(code)
  await guest.getByRole('button', { name: '加入房间', exact: true }).click()
  await guest.getByLabel('你的昵称').fill('老王')
  await guest.getByRole('button', { name: '选择头像 🐼', exact: true }).click()
  await guest.getByRole('button', { name: '准备好了，入场' }).click()
  await waitReady(guest)
  await expect(owner.locator('.lobby-player')).toHaveCount(2)
  await expect(guest.locator('.lobby-player')).toHaveCount(2)
  await owner.screenshot({ path: 'test-results/room-mobile.png', fullPage: true })
  await start(owner, '匿名投票')
  await expect(guest.locator('.countdown-overlay')).toHaveCount(0)
  await owner.locator('.player-choice').filter({ hasText: '老王' }).click()
  await expect(owner.getByText('你的选择已锁定，等待大家投票')).toBeVisible()
  await expect(guest.locator('.results-list')).toHaveCount(0)
  await guest.reload()
  await waitReady(guest)
  await expect(guest.locator('.game-stage')).toBeVisible()
  await guest.locator('.player-choice').filter({ hasText: '小辉' }).click()
  await expect(owner.getByText('大家的选择，揭晓！')).toBeVisible()
  await expect(guest.locator('.result-row.winner')).toHaveCount(2)
  await owner.screenshot({ path: 'test-results/vote-mobile.png', fullPage: true })
  await owner.getByRole('button', { name: '下一局', exact: true }).click()
  await expect(guest.getByText('ROUND 02', { exact: true })).toBeVisible()
  await expect(owner.locator('.countdown-overlay')).toHaveCount(0)
  await owner.getByRole('button', { name: '返回大厅 · 换个游戏' }).click()
  await start(owner, '摇骰子')
  await expect(guest.locator('.countdown-overlay')).toHaveCount(0)
  await owner.getByRole('button', { name: '摇骰子', exact: true }).click()
  await guest.getByRole('button', { name: '摇骰子', exact: true }).click()
  await expect(owner.getByText('手气排行榜')).toBeVisible()
  await expect(guest.locator('.result-row')).toHaveCount(2)
  await guestContext.setOffline(true)
  await expect(guest.getByRole('button', { name: '连接状态：离线', exact: true })).toBeVisible()
  await guestContext.setOffline(false)
  await waitReady(guest)
  await expect(guest.getByText('手气排行榜')).toBeVisible()
  await owner.getByRole('button', { name: '返回大厅 · 换个游戏' }).click()
  await start(owner, '幸运轮盘')
  await owner.getByRole('button', { name: '转动轮盘', exact: true }).click()
  await expect(owner.locator('.roulette-result')).toBeVisible()
  const result = await owner.locator('.roulette-result').textContent()
  await expect(guest.locator('.roulette-result')).toHaveText(result!)
  if (result === '指定一人') await owner.locator('.player-choice').first().click()
  await expect(owner.getByRole('button', { name: '下一局', exact: true })).toBeVisible()
  await owner.getByRole('button', { name: '返回大厅 · 换个游戏' }).click()
  await start(owner, '真心话大冒险')
  await expect(guest.locator('.countdown-overlay')).toHaveCount(0)
  const selected = (await owner.getByRole('button', { name: '真心话 聊点不一样的' }).isEnabled())
    ? owner
    : guest
  await selected.getByRole('button', { name: '真心话 聊点不一样的' }).click()
  await expect(owner.locator('.revealed-card h3')).not.toBeEmpty()
  await expect(guest.locator('.revealed-card h3')).toHaveText(
    (await owner.locator('.revealed-card h3').textContent())!,
  )
  await owner.getByRole('button', { name: '返回大厅 · 换个游戏' }).click()
  await start(owner, '默契测试')
  await expect(guest.locator('.countdown-overlay')).toHaveCount(0)
  await owner.locator('.answer-options button').first().click()
  await expect(guest.locator('.answer-reveal')).toHaveCount(0)
  await guest.locator('.answer-options button').first().click()
  await expect(owner.getByText('心有灵犀，默契 +1！')).toBeVisible()
  await expect(guest.getByText('心有灵犀，默契 +1！')).toBeVisible()
  await owner.reload()
  await waitReady(owner)
  await expect(owner.getByRole('button', { name: '下一局', exact: true })).toBeVisible()
  await owner.getByRole('button', { name: '返回大厅 · 换个游戏' }).click()
  await owner.getByRole('button', { name: '退出房间', exact: true }).click()
  await owner.getByRole('button', { name: '确认离开', exact: true }).click()
  await expect(owner).toHaveURL(`${base}/`)
  await expect(guest.getByRole('button', { name: '房间设置', exact: true })).toBeVisible()
  await guest.getByRole('button', { name: '房间设置', exact: true }).click()
  await guest.getByRole('button', { name: '关闭这个房间', exact: true }).click()
  await guest.getByRole('button', { name: '确认离开', exact: true }).click()
  await expect(guest).toHaveURL(`${base}/`)
  await ownerContext.close()
  await guestContext.close()
})
test('homepage fits 375, 390, 430 and desktop and rules work', async ({ page }) => {
  for (const width of [375, 390, 430, 1440]) {
    await page.setViewportSize({ width, height: width > 500 ? 1000 : 844 })
    await page.goto('/')
    await expect(page.getByRole('heading', { name: /今晚/ })).toBeVisible()
    expect(
      await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),
    ).toBe(true)
    await page.screenshot({ path: `test-results/home-${width}.png`, fullPage: true })
  }
  await page.locator('.game-card').first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: '就玩这个' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
})
